version: '2'
services:
    av-api:
        image: byuoitav/rpi-av-api:development
        ports:
            - "8000:8000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
    pjlink-microservice:
        image: byuoitav/rpi-pjlink-microservice:development
        ports:
            - "8005:8005"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PJLINK_PORT=$PJLINK_PORT
            - PJLINK_PASS=$PJLINK_PASS
        network_mode: "host"
        restart: always
        tty: true
    configuration-database-microservice:
        image: byuoitav/rpi-configuration-database-microservice:development
        ports:
            - "8006:8006"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_USERNAME=$CONFIGURATION_DATABASE_USERNAME
            - CONFIGURATION_DATABASE_PASSWORD=$CONFIGURATION_DATABASE_PASSWORD
            - CONFIGURATION_DATABASE_HOST=$CONFIGURATION_DATABASE_HOST
            - CONFIGURATION_DATABASE_PORT=$CONFIGURATION_DATABASE_PORT
            - CONFIGURATION_DATABASE_NAME=$CONFIGURATION_DATABASE_NAME
        network_mode: "host"
        restart: always
        tty: true
    sony-control-microservice:
        image: byuoitav/rpi-sony-control-microservice:development
        ports:
            - "8007:8007"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - SONY_TV_PSK=$SONY_TV_PSK
        network_mode: "host"
        restart: always
        tty: true
    london-audio-microservice:
        image: byuoitav/rpi-london-audio-microservice:development
        ports:
            - "8009:8009"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    pulse-eight-neo-microservice:
        image: byuoitav/rpi-pulse-eight-neo-microservice:development
        ports:
            - "8011:8011"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    kramer-microservice:
        image: byuoitav/rpi-kramer-microservice:development
        ports:
            - "8014:8014"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    adcp-control-microservice:
        image: byuoitav/rpi-adcp-control-microservice:development
        ports:
            - "8012:8012"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
    av-api-rpc:
        image: byuoitav/rpi-av-api-rpc:development
        ports:
            - "8100:8100"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
        network_mode: "host"
        restart: always
        tty: true
    touchpanel-ui-microservice:
        image: byuoitav/rpi-touchpanel-ui-microservice:development
        ports:
            - "8888:8888"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - HELP_SLACKBOT_WEBHOOK=$HELP_SLACKBOT_WEBHOOK
            - UI_CONFIGURATION_ADDRESS=$UI_CONFIGURATION_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
    event-router-microservice:
        image: byuoitav/rpi-event-router-microservice:development
        ports:
            - "7000:7000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
    event-translator-microservice:
        image: byuoitav/rpi-event-translator-microservice:development
        ports:
            - "7002:7002"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - ELASTIC_API_EVENTS_DEV=$ELASTIC_API_EVENTS_DEV
        network_mode: "host"
        restart: "always"
        tty: true
    device-monitoring-microservice:
        image: byuoitav/rpi-device-monitoring-microservice:development
        ports:
            - "10000:10000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - DEVICE_PING_INTERVAL=$DEVICE_PING_INTERVAL
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
