version: '2'
services:
    av-api:
        image: byuoitav/rpi-av-api:production
        ports:
            - "8000:8000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - ROOM_SYSTEM=$ROOM_SYSTEM
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    pjlink-microservice:
        image: byuoitav/rpi-pjlink-microservice:production
        ports:
            - "8005:8005"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PJLINK_PORT=$PJLINK_PORT
            - PJLINK_PASS=$PJLINK_PASS
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    configuration-database-microservice:
        image: byuoitav/rpi-configuration-database-microservice:production
        ports:
            - "8006:8006"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_USERNAME=$CONFIGURATION_DATABASE_USERNAME
            - CONFIGURATION_DATABASE_PASSWORD=$CONFIGURATION_DATABASE_PASSWORD
            - CONFIGURATION_DATABASE_HOST=$CONFIGURATION_DATABASE_HOST
            - CONFIGURATION_DATABASE_PORT=$CONFIGURATION_DATABASE_PORT
            - CONFIGURATION_DATABASE_NAME=$CONFIGURATION_DATABASE_NAME
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    sony-control-microservice:
        image: byuoitav/rpi-sony-control-microservice:production
        ports:
            - "8007:8007"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - SONY_TV_PSK=$SONY_TV_PSK
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    london-audio-microservice:
        image: byuoitav/rpi-london-audio-microservice:production
        ports:
            - "8009:8009"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    pulse-eight-neo-microservice:
        image: byuoitav/rpi-pulse-eight-neo-microservice:production
        ports:
            - "8011:8011"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    kramer-microservice:
        image: byuoitav/rpi-kramer-microservice:production
        ports:
            - "8014:8014"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    adcp-control-microservice:
        image: byuoitav/rpi-adcp-control-microservice:production
        ports:
            - "8012:8012"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    touchpanel-ui-microservice:
        image: byuoitav/rpi-touchpanel-ui-microservice:production
        ports:
            - "8888:8888"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - ROOM_SYSTEM=$ROOM_SYSTEM
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - HELP_SLACKBOT_WEBHOOK=$HELP_SLACKBOT_WEBHOOK
            - UI_CONFIGURATION_ADDRESS=$UI_CONFIGURATION_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: always
        tty: true
        logging:
            options:
                max-size: "100m"
    event-router-microservice:
        image: byuoitav/rpi-event-router-microservice:production
        ports:
            - "7000:7000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - ROOM_SYSTEM=$ROOM_SYSTEM
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_NODE_ADDRESSES=$EVENT_NODE_ADDRESSES
        network_mode: "host"
        restart: "always"
        tty: true
        logging:
            options:
                max-size: "100m"
    event-translator-microservice:
        image: byuoitav/rpi-event-translator-microservice:production
        ports:
            - "7002:7002"
        environment:
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
        logging:
            options:
                max-size: "100m"
    device-monitoring-microservice:
        image: byuoitav/rpi-device-monitoring-microservice:production
        ports:
            - "10000:10000"
        environment:
            - PI_HOSTNAME=$PI_HOSTNAME
            - ROOM_SYSTEM=$ROOM_SYSTEM
            - DEVICE_PING_INTERVAL=$DEVICE_PING_INTERVAL
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
        tty: true
        logging:
            options:
                max-size: "100m"
    shure-audio-microservice:
        image: byuoitav/rpi-shure-audio-microservice:production
        ports:
            - "8013:8013"
        environment:
            - ELASTIC_API_EVENTS=$ELASTIC_API_EVENTS
            - LOCAL_ENVIRONMENT=$LOCAL_ENVIRONMENT
            - PI_HOSTNAME=$PI_HOSTNAME
            - ROOM_SYSTEM=$ROOM_SYSTEM
            - CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS=$CONFIGURATION_DATABASE_MICROSERVICE_ADDRESS
            - EVENT_ROUTER_ADDRESS=$EVENT_ROUTER_ADDRESS
        network_mode: "host"
        restart: "always"
        logging:
            options:
                max-size: "100m"
